/**
 * Pre-defined starter packs for common use cases.
 * These curated bundles help users quickly get the icons they need.
 */

export interface StarterPack {
  id: string;
  name: string;
  description: string;
  iconNames: string[];
  color: string;
}

export const STARTER_PACKS: StarterPack[] = [
  {
    id: "shadcn-ui",
    name: "shadcn/ui Components",
    description: "Icons used by shadcn/ui component examples and patterns",
    color: "zinc",
    iconNames: [
      // Form validation & status
      "check",
      "check-circle-2",
      "circle",
      "circle-check",
      "circle-x",
      "alert-circle",
      "alert-triangle",
      "info",
      // Navigation & menus
      "chevron-down",
      "chevron-up",
      "chevron-left",
      "chevron-right",
      "menu",
      "x",
      // Actions
      "plus",
      "minus",
      "edit",
      "edit-2",
      "trash",
      "trash-2",
      "copy",
      "more-horizontal",
      "more-vertical",
      // Loading
      "loader",
      "loader-2",
      // Table sorting & arrows
      "arrow-up-down",
      "arrow-up",
      "arrow-down",
      "arrow-left",
      "arrow-right",
      // Common UI elements
      "search",
      "settings",
      "user",
      "users",
      "log-out",
      "log-in",
      "eye",
      "eye-off",
      "calendar",
      "clock",
      "mail",
      "credit-card",
      "image",
      "upload",
      "download",
      "external-link",
      "link",
    ],
  },
  {
    id: "dashboard",
    name: "Dashboard Essentials",
    description: "Core UI icons for admin dashboards",
    color: "cyan",
    iconNames: [
      "home",
      "settings",
      "user",
      "users",
      "bell",
      "search",
      "menu",
      "x",
      "check",
      "plus",
      "minus",
      "edit",
      "trash",
      "eye",
      "eye-off",
      "log-out",
      "log-in",
      "lock",
      "unlock",
      "key",
      "shield",
      "activity",
      "bar-chart",
      "pie-chart",
      "trending-up",
      "trending-down",
      "calendar",
      "clock",
      "filter",
      "sliders",
    ],
  },
  {
    id: "ecommerce",
    name: "E-commerce Kit",
    description: "Shopping, payments, and product icons",
    color: "emerald",
    iconNames: [
      "shopping-cart",
      "shopping-bag",
      "credit-card",
      "wallet",
      "package",
      "truck",
      "store",
      "tag",
      "percent",
      "receipt",
      "gift",
      "heart",
      "star",
      "thumbs-up",
      "thumbs-down",
      "share",
      "bookmark",
      "box",
      "archive",
      "scan",
      "qr-code",
      "barcode",
      "scale",
      "calculator",
    ],
  },
  {
    id: "social",
    name: "Social Media Pack",
    description: "Engagement and social interaction icons",
    color: "pink",
    iconNames: [
      "heart",
      "message-circle",
      "message-square",
      "send",
      "share",
      "share-2",
      "bookmark",
      "flag",
      "bell",
      "at-sign",
      "hash",
      "link",
      "external-link",
      "user-plus",
      "user-minus",
      "users",
      "smile",
      "frown",
      "meh",
      "thumbs-up",
      "thumbs-down",
      "award",
      "zap",
      "trending-up",
    ],
  },
  {
    id: "files",
    name: "File Manager",
    description: "Documents, folders, and file operations",
    color: "amber",
    iconNames: [
      "file",
      "file-text",
      "file-plus",
      "file-minus",
      "file-check",
      "file-x",
      "folder",
      "folder-open",
      "folder-plus",
      "folder-minus",
      "upload",
      "download",
      "cloud",
      "cloud-upload",
      "cloud-download",
      "save",
      "copy",
      "clipboard",
      "scissors",
      "paperclip",
      "image",
      "video",
      "music",
      "archive",
    ],
  },
  {
    id: "navigation",
    name: "Navigation Set",
    description: "Arrows, menus, and directional icons",
    color: "violet",
    iconNames: [
      "arrow-up",
      "arrow-down",
      "arrow-left",
      "arrow-right",
      "chevron-up",
      "chevron-down",
      "chevron-left",
      "chevron-right",
      "chevrons-up",
      "chevrons-down",
      "chevrons-left",
      "chevrons-right",
      "corner-down-left",
      "corner-down-right",
      "corner-up-left",
      "corner-up-right",
      "move",
      "maximize",
      "minimize",
      "menu",
      "more-horizontal",
      "more-vertical",
      "grid",
      "list",
    ],
  },
  {
    id: "media",
    name: "Media Controls",
    description: "Play, pause, and media player icons",
    color: "rose",
    iconNames: [
      "play",
      "pause",
      "stop-circle",
      "skip-back",
      "skip-forward",
      "rewind",
      "fast-forward",
      "volume",
      "volume-1",
      "volume-2",
      "volume-x",
      "mic",
      "mic-off",
      "video",
      "video-off",
      "camera",
      "image",
      "film",
      "tv",
      "monitor",
      "headphones",
      "speaker",
      "radio",
      "podcast",
    ],
  },
  {
    id: "developer",
    name: "Developer Tools",
    description: "Terminal, code, and dev workflow icons",
    color: "slate",
    iconNames: [
      "terminal",
      "code",
      "git-branch",
      "git-commit",
      "git-merge",
      "bug",
      "wrench",
      "hammer",
      "cpu",
      "server",
      "database",
      "globe",
      "wifi",
      "hard-drive",
      "layers",
      "box",
      "package",
      "zap",
      "tool",
      "settings",
    ],
  },
  {
    id: "communication",
    name: "Communication",
    description: "Email, chat, and messaging icons",
    color: "blue",
    iconNames: [
      "mail",
      "inbox",
      "send",
      "phone",
      "phone-call",
      "phone-off",
      "message-circle",
      "message-square",
      "video",
      "voicemail",
      "contact",
      "at-sign",
      "paperclip",
      "reply",
      "forward",
    ],
  },
  {
    id: "weather",
    name: "Weather & Nature",
    description: "Sun, rain, and environmental icons",
    color: "sky",
    iconNames: [
      "sun",
      "moon",
      "cloud",
      "cloud-rain",
      "cloud-snow",
      "wind",
      "thermometer",
      "droplet",
      "umbrella",
      "sunrise",
      "sunset",
      "snowflake",
      "rainbow",
      "tornado",
      "waves",
    ],
  },
  {
    id: "health",
    name: "Health & Wellness",
    description: "Fitness, medical, and wellness icons",
    color: "red",
    iconNames: [
      "heart",
      "heart-pulse",
      "activity",
      "apple",
      "dumbbell",
      "bike",
      "footprints",
      "eye",
      "ear",
      "hand",
      "brain",
      "bone",
      "droplet",
      "pill",
      "syringe",
    ],
  },
  {
    id: "editor",
    name: "Text Editor",
    description: "Formatting and rich text icons",
    color: "indigo",
    iconNames: [
      "bold",
      "italic",
      "underline",
      "strikethrough",
      "align-left",
      "align-center",
      "align-right",
      "list",
      "list-ordered",
      "heading",
      "quote",
      "link",
      "code",
      "type",
      "text",
    ],
  },
  {
    id: "status",
    name: "Status & Feedback",
    description: "Alerts, validation, and state icons",
    color: "orange",
    iconNames: [
      "check-circle",
      "x-circle",
      "alert-circle",
      "alert-triangle",
      "info",
      "help-circle",
      "loader",
      "refresh-cw",
      "check",
      "x",
      "ban",
      "clock",
      "hourglass",
      "timer",
      "bell",
    ],
  },
  {
    id: "location",
    name: "Maps & Location",
    description: "Navigation, places, and travel icons",
    color: "teal",
    iconNames: [
      "map",
      "map-pin",
      "navigation",
      "compass",
      "locate",
      "route",
      "milestone",
      "flag",
      "globe",
      "earth",
      "pin",
      "signpost",
      "parking",
      "plane",
      "car",
    ],
  },
  {
    id: "finance",
    name: "Finance & Banking",
    description: "Money, payments, and financial icons",
    color: "green",
    iconNames: [
      "wallet",
      "credit-card",
      "banknote",
      "coins",
      "piggy-bank",
      "landmark",
      "percent",
      "receipt",
      "trending-up",
      "trending-down",
      "chart",
      "dollar-sign",
      "euro",
      "bitcoin",
      "building",
    ],
  },
  {
    id: "security",
    name: "Security & Auth",
    description: "Locks, shields, and verification icons",
    color: "zinc",
    iconNames: [
      "lock",
      "unlock",
      "key",
      "shield",
      "shield-check",
      "fingerprint",
      "scan",
      "eye",
      "eye-off",
      "user-check",
      "badge-check",
      "verified",
      "alert-triangle",
      "ban",
      "lock-keyhole",
    ],
  },
  {
    id: "education",
    name: "Education & Learning",
    description: "Books, study, and academic icons",
    color: "purple",
    iconNames: [
      "book",
      "book-open",
      "graduation-cap",
      "award",
      "trophy",
      "lightbulb",
      "pencil",
      "notebook",
      "library",
      "school",
      "backpack",
      "ruler",
      "calculator",
      "globe",
      "bookmark",
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────────
  // Development & DevOps
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "cicd",
    name: "CI/CD Pipeline",
    description: "Git workflows, deployments, and build automation",
    color: "orange",
    iconNames: [
      "git-branch",
      "git-commit",
      "git-merge",
      "git-pull-request",
      "rocket",
      "package",
      "box",
      "check-circle",
      "x-circle",
      "clock",
      "loader",
      "refresh-cw",
      "play",
      "pause",
      "terminal",
      "webhook",
    ],
  },
  {
    id: "database-kit",
    name: "Database Kit",
    description: "Tables, schemas, queries, and data management",
    color: "emerald",
    iconNames: [
      "database",
      "table",
      "table-2",
      "columns",
      "rows",
      "key",
      "link",
      "unlink",
      "search",
      "filter",
      "sort-asc",
      "sort-desc",
      "plus",
      "minus",
      "edit",
      "trash",
    ],
  },
  {
    id: "api-builder",
    name: "API Builder",
    description: "Endpoints, requests, responses, and integrations",
    color: "violet",
    iconNames: [
      "globe",
      "server",
      "cloud",
      "send",
      "inbox",
      "arrow-right-left",
      "key",
      "lock",
      "unlock",
      "shield",
      "zap",
      "clock",
      "timer",
      "gauge",
      "webhook",
      "code",
    ],
  },
  {
    id: "testing-suite",
    name: "Testing Suite",
    description: "Test coverage, assertions, and debugging",
    color: "green",
    iconNames: [
      "check",
      "check-circle",
      "x",
      "x-circle",
      "bug",
      "search",
      "target",
      "crosshair",
      "eye",
      "eye-off",
      "shield-check",
      "clipboard-check",
      "list-checks",
      "badge-check",
      "circle-dot",
      "flask-conical",
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────────
  // Product & Business
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "analytics",
    name: "Analytics Dashboard",
    description: "Charts, metrics, funnels, and data visualization",
    color: "cyan",
    iconNames: [
      "bar-chart",
      "bar-chart-2",
      "bar-chart-3",
      "line-chart",
      "pie-chart",
      "trending-up",
      "trending-down",
      "activity",
      "gauge",
      "target",
      "users",
      "user-plus",
      "eye",
      "mouse-pointer-click",
      "funnel",
      "chart-area",
    ],
  },
  {
    id: "project-management",
    name: "Project Management",
    description: "Kanban, sprints, milestones, and task tracking",
    color: "blue",
    iconNames: [
      "kanban",
      "layout-grid",
      "layout-list",
      "list-todo",
      "list-checks",
      "check-square",
      "square",
      "circle",
      "flag",
      "milestone",
      "calendar",
      "calendar-days",
      "clock",
      "timer",
      "users",
      "target",
    ],
  },
  {
    id: "customer-support",
    name: "Customer Support",
    description: "Tickets, chat, help desk, and feedback",
    color: "pink",
    iconNames: [
      "ticket",
      "message-circle",
      "message-square",
      "messages-square",
      "headphones",
      "headset",
      "phone",
      "mail",
      "inbox",
      "help-circle",
      "life-buoy",
      "thumbs-up",
      "thumbs-down",
      "star",
      "smile",
      "frown",
    ],
  },
  {
    id: "onboarding",
    name: "Onboarding Flow",
    description: "Steps, progress, tutorials, and welcome screens",
    color: "teal",
    iconNames: [
      "rocket",
      "sparkles",
      "wand-2",
      "lightbulb",
      "circle-help",
      "info",
      "list-ordered",
      "check-circle",
      "arrow-right",
      "chevron-right",
      "user-plus",
      "hand-wave",
      "party-popper",
      "gift",
      "flag",
      "target",
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────────
  // Content & Media
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "rich-text-editor",
    name: "Rich Text Editor",
    description: "Formatting, lists, headings, and embeds",
    color: "indigo",
    iconNames: [
      "bold",
      "italic",
      "underline",
      "strikethrough",
      "heading-1",
      "heading-2",
      "heading-3",
      "list",
      "list-ordered",
      "quote",
      "code",
      "link",
      "image",
      "video",
      "table",
      "align-left",
      "align-center",
      "align-right",
      "align-justify",
    ],
  },
  {
    id: "image-editor",
    name: "Image Editor",
    description: "Crop, rotate, filters, and adjustments",
    color: "rose",
    iconNames: [
      "crop",
      "rotate-cw",
      "rotate-ccw",
      "flip-horizontal",
      "flip-vertical",
      "zoom-in",
      "zoom-out",
      "move",
      "maximize",
      "minimize",
      "layers",
      "palette",
      "paintbrush",
      "eraser",
      "wand-2",
      "image",
    ],
  },
  {
    id: "audio-podcast",
    name: "Audio & Podcast",
    description: "Waveforms, playback, and audio production",
    color: "purple",
    iconNames: [
      "mic",
      "mic-off",
      "headphones",
      "volume",
      "volume-1",
      "volume-2",
      "volume-x",
      "play",
      "pause",
      "skip-back",
      "skip-forward",
      "rewind",
      "fast-forward",
      "radio",
      "podcast",
      "music",
    ],
  },
  {
    id: "video-player",
    name: "Video Player",
    description: "Playback controls, subtitles, and streaming",
    color: "red",
    iconNames: [
      "play",
      "pause",
      "stop-circle",
      "skip-back",
      "skip-forward",
      "rewind",
      "fast-forward",
      "volume",
      "volume-x",
      "maximize",
      "minimize",
      "settings",
      "subtitles",
      "captions",
      "picture-in-picture",
      "tv",
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────────
  // E-commerce Extensions
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "inventory",
    name: "Inventory Management",
    description: "Stock, warehouse, shipping, and returns",
    color: "amber",
    iconNames: [
      "package",
      "packages",
      "box",
      "boxes",
      "warehouse",
      "forklift",
      "truck",
      "ship",
      "plane",
      "scan",
      "scan-barcode",
      "qr-code",
      "clipboard-list",
      "undo-2",
      "redo-2",
      "archive",
    ],
  },
  {
    id: "subscription-saas",
    name: "Subscription & SaaS",
    description: "Plans, billing cycles, and usage meters",
    color: "violet",
    iconNames: [
      "credit-card",
      "receipt",
      "calendar",
      "calendar-clock",
      "repeat",
      "infinity",
      "gauge",
      "chart-bar",
      "trending-up",
      "arrow-up-circle",
      "arrow-down-circle",
      "crown",
      "gem",
      "sparkles",
      "zap",
      "rocket",
    ],
  },
  {
    id: "marketplace",
    name: "Marketplace",
    description: "Sellers, reviews, disputes, and verification",
    color: "emerald",
    iconNames: [
      "store",
      "shopping-bag",
      "users",
      "user-check",
      "badge-check",
      "star",
      "star-half",
      "message-square",
      "flag",
      "shield",
      "shield-check",
      "scale",
      "gavel",
      "handshake",
      "lock",
      "eye",
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────────
  // User & Social
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "profile-identity",
    name: "Profile & Identity",
    description: "Avatars, badges, verification, and privacy",
    color: "blue",
    iconNames: [
      "user",
      "user-circle",
      "user-check",
      "user-x",
      "user-plus",
      "user-minus",
      "badge-check",
      "verified",
      "shield",
      "shield-check",
      "key",
      "fingerprint",
      "lock",
      "eye",
      "eye-off",
      "settings",
    ],
  },
  {
    id: "notifications",
    name: "Notifications Center",
    description: "Alerts, mentions, digests, and preferences",
    color: "orange",
    iconNames: [
      "bell",
      "bell-ring",
      "bell-off",
      "bell-plus",
      "bell-minus",
      "at-sign",
      "hash",
      "mail",
      "inbox",
      "message-circle",
      "volume-x",
      "filter",
      "settings",
      "trash",
      "check",
      "x",
    ],
  },
  {
    id: "collaboration",
    name: "Collaboration",
    description: "Comments, mentions, presence, and reactions",
    color: "cyan",
    iconNames: [
      "message-circle",
      "message-square",
      "at-sign",
      "hash",
      "link",
      "share",
      "share-2",
      "users",
      "user-plus",
      "mouse-pointer",
      "mouse-pointer-2",
      "smile",
      "heart",
      "thumbs-up",
      "reply",
      "forward",
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────────
  // Utility Packs
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "form-elements",
    name: "Form Elements",
    description: "Inputs, selects, checkboxes, and controls",
    color: "slate",
    iconNames: [
      "square",
      "check-square",
      "circle",
      "circle-dot",
      "toggle-left",
      "toggle-right",
      "sliders",
      "sliders-horizontal",
      "text-cursor",
      "text-cursor-input",
      "calendar",
      "clock",
      "chevron-down",
      "search",
      "x",
      "check",
    ],
  },
  {
    id: "status-indicators",
    name: "Status Indicators",
    description: "Online, offline, loading, and state icons",
    color: "green",
    iconNames: [
      "circle",
      "circle-dot",
      "check-circle",
      "x-circle",
      "alert-circle",
      "alert-triangle",
      "info",
      "help-circle",
      "loader",
      "loader-2",
      "refresh-cw",
      "clock",
      "hourglass",
      "wifi",
      "wifi-off",
      "signal",
    ],
  },
  {
    id: "accessibility",
    name: "Accessibility",
    description: "Screen readers, captions, and assistive tech",
    color: "purple",
    iconNames: [
      "accessibility",
      "eye",
      "eye-off",
      "ear",
      "ear-off",
      "volume",
      "volume-x",
      "captions",
      "subtitles",
      "keyboard",
      "mouse-pointer",
      "hand",
      "zoom-in",
      "zoom-out",
      "sun",
      "moon",
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────────
  // Brand Icon Packs (Simple Icons)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: "brand-ai",
    name: "AI & LLM Brands",
    description: "Logos for AI companies and LLM providers",
    color: "violet",
    iconNames: [
      "anthropic",
      "claude",
      "huggingface",
      "perplexity",
      "cohere",
      "googlegemini",
      "ollama",
      "replicate",
      "langchain",
      "deepmind",
      "clarifai",
      "elevenlabs",
      "meta",
      "githubcopilot",
      "modal",
    ],
  },
  {
    id: "brand-saas",
    name: "SaaS Tools",
    description: "Popular productivity and collaboration apps",
    color: "blue",
    iconNames: [
      "notion",
      "linear",
      "figma",
      "slack",
      "miro",
      "asana",
      "jira",
      "confluence",
      "trello",
      "airtable",
      "calendly",
      "loom",
      "intercom",
      "zendesk",
      "posthog",
      "mixpanel",
      "hotjar",
    ],
  },
  {
    id: "brand-devplatforms",
    name: "Developer Platforms",
    description: "Hosting, databases, and dev infrastructure",
    color: "emerald",
    iconNames: [
      "github",
      "gitlab",
      "vercel",
      "netlify",
      "railway",
      "render",
      "supabase",
      "planetscale",
      "turso",
      "prisma",
      "drizzle",
      "firebase",
      "appwrite",
      "pocketbase",
      "clerk",
      "auth0",
      "resend",
    ],
  },
  {
    id: "brand-frontend",
    name: "Frontend & Frameworks",
    description: "JavaScript frameworks and UI libraries",
    color: "cyan",
    iconNames: [
      "react",
      "vuedotjs",
      "angular",
      "svelte",
      "nextdotjs",
      "nuxt",
      "astro",
      "remix",
      "typescript",
      "tailwindcss",
      "shadcnui",
      "radixui",
      "storybook",
      "vite",
      "turbo",
      "bun",
      "deno",
    ],
  },
  {
    id: "brand-devtools",
    name: "Dev Tools & IDEs",
    description: "Code editors, testing, and build tools",
    color: "slate",
    iconNames: [
      "cursor",
      "neovim",
      "vim",
      "intellijidea",
      "webstorm",
      "replit",
      "codesandbox",
      "stackblitz",
      "git",
      "gitkraken",
      "npm",
      "pnpm",
      "yarn",
      "jest",
      "vitest",
      "cypress",
      "chromatic",
    ],
  },
  {
    id: "brand-cloud",
    name: "Cloud & DevOps",
    description: "Infrastructure, CI/CD, and monitoring",
    color: "orange",
    iconNames: [
      "docker",
      "kubernetes",
      "terraform",
      "ansible",
      "googlecloud",
      "digitalocean",
      "cloudflare",
      "nginx",
      "apache",
      "githubactions",
      "circleci",
      "jenkins",
      "prometheus",
      "grafana",
      "datadog",
      "sentry",
      "newrelic",
    ],
  },
  {
    id: "brand-social",
    name: "Social & Content",
    description: "Social media and content platforms",
    color: "pink",
    iconNames: [
      "x",
      "instagram",
      "youtube",
      "tiktok",
      "threads",
      "bluesky",
      "mastodon",
      "discord",
      "reddit",
      "telegram",
      "whatsapp",
      "medium",
      "substack",
      "hashnode",
      "devdotto",
      "twitch",
      "spotify",
    ],
  },
  {
    id: "brand-payments",
    name: "Payments & Commerce",
    description: "Payment processors and e-commerce platforms",
    color: "green",
    iconNames: [
      "stripe",
      "paypal",
      "shopify",
      "woocommerce",
      "square",
      "lemonsqueezy",
      "paddle",
      "gumroad",
      "razorpay",
      "etsy",
      "ebay",
    ],
  },
  {
    id: "brand-databases",
    name: "Databases",
    description: "SQL, NoSQL, and search databases",
    color: "amber",
    iconNames: [
      "postgresql",
      "mysql",
      "mongodb",
      "redis",
      "sqlite",
      "mariadb",
      "elasticsearch",
      "neo4j",
      "arangodb",
      "fauna",
      "algolia",
      "meilisearch",
    ],
  },
];

